site_name: Sauvian villa

theme:
  name: material
  palette:
    primary: indigo
    accent: light blue
    

use_directory_urls: false

nav:
    - Welcome: index.md
    - Villa information: villa.md
    - Local amenities: localamenities.md
    - Local beaches: localbeaches.md
    - Days out: daysout.md
    - Before you leave: endofstay.md
